import type { Recipe } from './types';

export const legacyRecipeSeedData = [
  {
    name: 'Krem waniliowy bazowy',
    recipeId: 'basecreamvanilla',
    defaultWeight: 500,
    ingredients: [
      { name: 'Mleko', amount: 400, unit: 'ml' },
      { name: 'Żółtka', amount: 80, unit: 'g' },
      { name: 'Cukier', amount: 80, unit: 'g' },
      { name: 'Mąka ziemniaczana', amount: 20, unit: 'g' },
      { name: 'Laska wanilii', amount: 1, unit: 'pcs' },
    ],
  },
  {
    name: 'Krem czekoladowy bazowy',
    recipeId: 'basecreamchocolate',
    defaultWeight: 600,
    ingredients: [
      { name: 'Śmietanka 30%', amount: 300, unit: 'ml' },
      { name: 'Mleko', amount: 200, unit: 'ml' },
      { name: 'Czekolada 70%', amount: 150, unit: 'g' },
      { name: 'Cukier', amount: 60, unit: 'g' },
    ],
  },
  {
    name: 'Biszkopt bazowy',
    recipeId: 'basesponge',
    defaultWeight: 800,
    ingredients: [
      { name: 'Jajka', amount: 200, unit: 'g' },
      { name: 'Cukier', amount: 180, unit: 'g' },
      { name: 'Mąka pszenna', amount: 180, unit: 'g' },
      { name: 'Mąka ziemniaczana', amount: 40, unit: 'g' },
    ],
  },
  {
    name: 'Ganache czekoladowy',
    recipeId: 'baseganache',
    defaultWeight: 400,
    ingredients: [
      { name: 'Czekolada 60–70%', amount: 200, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 200, unit: 'ml' },
    ],
  },
  {
    name: 'Kruche ciasto bazowe',
    recipeId: 'baseshortcrust',
    defaultWeight: 600,
    ingredients: [
      { name: 'Mąka pszenna', amount: 300, unit: 'g' },
      { name: 'Masło', amount: 200, unit: 'g' },
      { name: 'Cukier puder', amount: 80, unit: 'g' },
      { name: 'Jajko', amount: 1, unit: 'pcs' },
    ],
  },
  {
    name: 'Tarta cytrynowa',
    recipeId: 'dessertlemontart',
    defaultWeight: 900,
    ingredients: [
      {
        name: 'Kruche ciasto (bazowe)',
        amount: 400,
        unit: 'g',
        recipeId: 'baseshortcrust',
      },
      { name: 'Masło', amount: 120, unit: 'g' },
      { name: 'Cukier', amount: 150, unit: 'g' },
      { name: 'Sok z cytryn', amount: 150, unit: 'ml' },
      { name: 'Jajka', amount: 120, unit: 'g' },
    ],
  },
  {
    name: 'Monoporcja czekoladowa z ganache',
    recipeId: 'dessertchocomonop',
    defaultWeight: 200,
    ingredients: [
      {
        name: 'Ganache czekoladowy',
        amount: 80,
        unit: 'g',
        recipeId: 'baseganache',
      },
      { name: 'Biszkopt', amount: 40, unit: 'g', recipeId: 'basesponge' },
      { name: 'Czekolada 70%', amount: 20, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 60, unit: 'ml' },
    ],
  },
  {
    name: 'Sernik klasyczny',
    recipeId: 'dessertcheesecakeclassic',
    defaultWeight: 1500,
    ingredients: [
      { name: 'Twaróg mielony', amount: 1000, unit: 'g' },
      { name: 'Cukier', amount: 250, unit: 'g' },
      { name: 'Jajka', amount: 200, unit: 'g' },
      { name: 'Masło', amount: 80, unit: 'g' },
      { name: 'Mąka pszenna', amount: 30, unit: 'g' },
    ],
  },
  {
    name: 'Brownie czekoladowe',
    recipeId: 'dessertbrownie',
    defaultWeight: 900,
    ingredients: [
      { name: 'Masło', amount: 150, unit: 'g' },
      { name: 'Czekolada 70%', amount: 200, unit: 'g' },
      { name: 'Cukier', amount: 200, unit: 'g' },
      { name: 'Mąka pszenna', amount: 100, unit: 'g' },
      { name: 'Jajka', amount: 150, unit: 'g' },
    ],
  },
  {
    name: 'Tiramisu',
    recipeId: 'desserttiramisu',
    defaultWeight: 800,
    ingredients: [
      { name: 'Mascarpone', amount: 400, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 200, unit: 'ml' },
      { name: 'Cukier', amount: 80, unit: 'g' },
      { name: 'Biszkopty podłużne', amount: 150, unit: 'g' },
      { name: 'Kawa espresso', amount: 80, unit: 'ml' },
    ],
  },
  {
    name: 'Panna cotta malinowa',
    recipeId: 'dessertpannacottaraspberry',
    defaultWeight: 300,
    ingredients: [
      { name: 'Śmietanka 30%', amount: 200, unit: 'ml' },
      { name: 'Cukier', amount: 40, unit: 'g' },
      { name: 'Żelatyna', amount: 6, unit: 'g' },
      { name: 'Maliny', amount: 80, unit: 'g' },
    ],
  },
  {
    name: 'Beza pavlova mini',
    recipeId: 'dessertminipavlova',
    defaultWeight: 120,
    ingredients: [
      { name: 'Białka', amount: 60, unit: 'g' },
      { name: 'Cukier', amount: 120, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 40, unit: 'ml' },
      { name: 'Owoce świeże', amount: 40, unit: 'g' },
    ],
  },
  {
    name: 'Tarta czekoladowa',
    recipeId: 'desserttartchoco',
    defaultWeight: 850,
    ingredients: [
      {
        name: 'Kruche ciasto',
        amount: 350,
        unit: 'g',
        recipeId: 'baseshortcrust',
      },
      {
        name: 'Ganache czekoladowy',
        amount: 300,
        unit: 'g',
        recipeId: 'baseganache',
      },
      { name: 'Czekolada 70%', amount: 50, unit: 'g' },
    ],
  },
  {
    name: 'Tarta owocowa',
    recipeId: 'dessertfruittart',
    defaultWeight: 900,
    ingredients: [
      {
        name: 'Kruche ciasto',
        amount: 350,
        unit: 'g',
        recipeId: 'baseshortcrust',
      },
      {
        name: 'Krem waniliowy',
        amount: 300,
        unit: 'g',
        recipeId: 'basecreamvanilla',
      },
      { name: 'Owoce świeże', amount: 250, unit: 'g' },
    ],
  },
  {
    name: 'Kremówka',
    recipeId: 'dessertkremowka',
    defaultWeight: 900,
    ingredients: [
      { name: 'Ciasto francuskie', amount: 300, unit: 'g' },
      {
        name: 'Krem waniliowy',
        amount: 500,
        unit: 'g',
        recipeId: 'basecreamvanilla',
      },
    ],
  },
  {
    name: 'Ciasto marchewkowe',
    recipeId: 'dessertcarrotcake',
    defaultWeight: 1000,
    ingredients: [
      { name: 'Marchew', amount: 250, unit: 'g' },
      { name: 'Cukier', amount: 150, unit: 'g' },
      { name: 'Mąka pszenna', amount: 200, unit: 'g' },
      { name: 'Olej', amount: 120, unit: 'ml' },
      { name: 'Jajka', amount: 150, unit: 'g' },
    ],
  },
  {
    name: 'Makaronik waniliowy',
    recipeId: 'dessertmacaronvanilla',
    defaultWeight: 40,
    ingredients: [
      { name: 'Białka', amount: 30, unit: 'g' },
      { name: 'Cukier puder', amount: 40, unit: 'g' },
      { name: 'Mąka migdałowa', amount: 40, unit: 'g' },
      {
        name: 'Krem waniliowy',
        amount: 10,
        unit: 'g',
        recipeId: 'basecreamvanilla',
      },
    ],
  },
  {
    name: 'Suflet czekoladowy',
    recipeId: 'dessertchocosouffle',
    defaultWeight: 150,
    ingredients: [
      { name: 'Czekolada 70%', amount: 50, unit: 'g' },
      { name: 'Masło', amount: 20, unit: 'g' },
      { name: 'Jajka', amount: 100, unit: 'g' },
      { name: 'Cukier', amount: 20, unit: 'g' },
    ],
  },
  {
    name: 'Tarta słona karmelowa',
    recipeId: 'dessertsaltedcarameltart',
    defaultWeight: 900,
    ingredients: [
      {
        name: 'Kruche ciasto',
        amount: 350,
        unit: 'g',
        recipeId: 'baseshortcrust',
      },
      { name: 'Cukier', amount: 150, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 150, unit: 'ml' },
      { name: 'Masło', amount: 60, unit: 'g' },
      { name: 'Sól', amount: 2, unit: 'g' },
    ],
  },
  {
    name: 'Babeczki waniliowe',
    recipeId: 'dessertvanillacupcakes',
    defaultWeight: 400,
    ingredients: [
      { name: 'Mąka pszenna', amount: 160, unit: 'g' },
      { name: 'Cukier', amount: 120, unit: 'g' },
      { name: 'Masło', amount: 80, unit: 'g' },
      { name: 'Jajka', amount: 100, unit: 'g' },
      {
        name: 'Krem waniliowy',
        amount: 80,
        unit: 'g',
        recipeId: 'basecreamvanilla',
      },
    ],
  },
  {
    name: 'Tarta pistacjowa',
    recipeId: 'dessertpistachiotart',
    defaultWeight: 950,
    ingredients: [
      {
        name: 'Kruche ciasto',
        amount: 350,
        unit: 'g',
        recipeId: 'baseshortcrust',
      },
      { name: 'Pasta pistacjowa', amount: 100, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 200, unit: 'ml' },
      { name: 'Cukier', amount: 80, unit: 'g' },
      { name: 'Masło', amount: 40, unit: 'g' },
    ],
  },
  {
    name: 'Monoporcja malinowa',
    recipeId: 'dessertraspberrymonop',
    defaultWeight: 180,
    ingredients: [
      { name: 'Biszkopt', amount: 40, unit: 'g', recipeId: 'basesponge' },
      { name: 'Maliny', amount: 60, unit: 'g' },
      {
        name: 'Krem waniliowy',
        amount: 60,
        unit: 'g',
        recipeId: 'basecreamvanilla',
      },
    ],
  },
  {
    name: 'Ciasto jogurtowe',
    recipeId: 'dessertyogurtcake',
    defaultWeight: 900,
    ingredients: [
      { name: 'Jogurt naturalny', amount: 200, unit: 'g' },
      { name: 'Cukier', amount: 150, unit: 'g' },
      { name: 'Mąka pszenna', amount: 250, unit: 'g' },
      { name: 'Olej', amount: 120, unit: 'ml' },
      { name: 'Jajka', amount: 150, unit: 'g' },
    ],
  },
  {
    name: 'Czekoladowa rolada',
    recipeId: 'dessertchocoroll',
    defaultWeight: 1000,
    ingredients: [
      { name: 'Biszkopt', amount: 300, unit: 'g', recipeId: 'basesponge' },
      {
        name: 'Ganache czekoladowy',
        amount: 300,
        unit: 'g',
        recipeId: 'baseganache',
      },
      { name: 'Dżem malinowy', amount: 100, unit: 'g' },
    ],
  },
  {
    name: 'Mus czekoladowy',
    recipeId: 'dessertchocomousse',
    defaultWeight: 300,
    ingredients: [
      { name: 'Czekolada 70%', amount: 120, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 150, unit: 'ml' },
      { name: 'Jajka', amount: 100, unit: 'g' },
    ],
  },
  {
    name: 'Tarta mango',
    recipeId: 'dessertmangotart',
    defaultWeight: 900,
    ingredients: [
      {
        name: 'Kruche ciasto',
        amount: 350,
        unit: 'g',
        recipeId: 'baseshortcrust',
      },
      { name: 'Puree mango', amount: 200, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 150, unit: 'ml' },
      { name: 'Cukier', amount: 80, unit: 'g' },
      { name: 'Żelatyna', amount: 6, unit: 'g' },
    ],
  },
] satisfies Recipe[];
