import type { Recipe } from './types';

export const dessertMiscSeedData = [
  {
    name: 'Monoporcja czekoladowa z ganache',
    recipeId: 'dessertchocomonop',
    defaultWeight: 200,
    ingredients: [
      {
        name: 'Ganache czekoladowy',
        amount: 80,
        unit: 'g',
        recipeId: 'baseganache',
      },
      { name: 'Biszkopt', amount: 40, unit: 'g', recipeId: 'basesponge' },
      { name: 'Czekolada 70%', amount: 20, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 60, unit: 'ml' },
    ],
    instructions: [],
  },
  {
    name: 'Sernik klasyczny',
    recipeId: 'dessertcheesecakeclassic',
    defaultWeight: 1500,
    ingredients: [
      { name: 'Twaróg mielony', amount: 1000, unit: 'g' },
      { name: 'Cukier', amount: 250, unit: 'g' },
      { name: 'Jajka', amount: 200, unit: 'g' },
      { name: 'Masło', amount: 80, unit: 'g' },
      { name: 'Mąka pszenna', amount: 30, unit: 'g' },
    ],
    instructions: [],
  },
  {
    name: 'Brownie czekoladowe',
    recipeId: 'dessertbrownie',
    defaultWeight: 900,
    ingredients: [
      { name: 'Masło', amount: 150, unit: 'g' },
      { name: 'Czekolada 70%', amount: 200, unit: 'g' },
      { name: 'Cukier', amount: 200, unit: 'g' },
      { name: 'Mąka pszenna', amount: 100, unit: 'g' },
      { name: 'Jajka', amount: 150, unit: 'g' },
    ],
    instructions: [],
  },
  {
    name: 'Tiramisu',
    recipeId: 'desserttiramisu',
    defaultWeight: 800,
    ingredients: [
      { name: 'Mascarpone', amount: 400, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 200, unit: 'ml' },
      { name: 'Cukier', amount: 80, unit: 'g' },
      { name: 'Biszkopty podłużne', amount: 150, unit: 'g' },
      { name: 'Kawa espresso', amount: 80, unit: 'ml' },
    ],
    instructions: [],
  },
  {
    name: 'Panna cotta malinowa',
    recipeId: 'dessertpannacottaraspberry',
    defaultWeight: 300,
    ingredients: [
      { name: 'Śmietanka 30%', amount: 200, unit: 'ml' },
      { name: 'Cukier', amount: 40, unit: 'g' },
      { name: 'Żelatyna', amount: 6, unit: 'g' },
      { name: 'Maliny', amount: 80, unit: 'g' },
    ],
    instructions: [],
  },
  {
    name: 'Beza pavlova mini',
    recipeId: 'dessertminipavlova',
    defaultWeight: 120,
    ingredients: [
      { name: 'Białka', amount: 60, unit: 'g' },
      { name: 'Cukier', amount: 120, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 40, unit: 'ml' },
      { name: 'Owoce świeże', amount: 40, unit: 'g' },
    ],
    instructions: [],
  },
  {
    name: 'Kremówka',
    recipeId: 'dessertkremowka',
    defaultWeight: 900,
    ingredients: [
      { name: 'Ciasto francuskie', amount: 300, unit: 'g' },
      {
        name: 'Krem waniliowy',
        amount: 500,
        unit: 'g',
        recipeId: 'basecreamvanilla',
      },
    ],
    instructions: [],
  },
  {
    name: 'Ciasto marchewkowe',
    recipeId: 'dessertcarrotcake',
    defaultWeight: 1000,
    ingredients: [
      { name: 'Marchew', amount: 250, unit: 'g' },
      { name: 'Cukier', amount: 150, unit: 'g' },
      { name: 'Mąka pszenna', amount: 200, unit: 'g' },
      { name: 'Olej', amount: 120, unit: 'ml' },
      { name: 'Jajka', amount: 150, unit: 'g' },
    ],
    instructions: [],
  },
  {
    name: 'Makaronik waniliowy',
    recipeId: 'dessertmacaronvanilla',
    defaultWeight: 40,
    ingredients: [
      { name: 'Białka', amount: 30, unit: 'g' },
      { name: 'Cukier puder', amount: 40, unit: 'g' },
      { name: 'Mąka migdałowa', amount: 40, unit: 'g' },
      {
        name: 'Krem waniliowy',
        amount: 10,
        unit: 'g',
        recipeId: 'basecreamvanilla',
      },
    ],
    instructions: [],
  },
  {
    name: 'Suflet czekoladowy',
    recipeId: 'dessertchocosouffle',
    defaultWeight: 150,
    ingredients: [
      { name: 'Czekolada 70%', amount: 50, unit: 'g' },
      { name: 'Masło', amount: 20, unit: 'g' },
      { name: 'Jajka', amount: 100, unit: 'g' },
      { name: 'Cukier', amount: 20, unit: 'g' },
    ],
    instructions: [],
  },
  {
    name: 'Babeczki waniliowe',
    recipeId: 'dessertvanillacupcakes',
    defaultWeight: 400,
    ingredients: [
      { name: 'Mąka pszenna', amount: 160, unit: 'g' },
      { name: 'Cukier', amount: 120, unit: 'g' },
      { name: 'Masło', amount: 80, unit: 'g' },
      { name: 'Jajka', amount: 100, unit: 'g' },
      {
        name: 'Krem waniliowy',
        amount: 80,
        unit: 'g',
        recipeId: 'basecreamvanilla',
      },
    ],
    instructions: [],
  },
  {
    name: 'Monoporcja malinowa',
    recipeId: 'dessertraspberrymonop',
    defaultWeight: 180,
    ingredients: [
      { name: 'Biszkopt', amount: 40, unit: 'g', recipeId: 'basesponge' },
      { name: 'Maliny', amount: 60, unit: 'g' },
      {
        name: 'Krem waniliowy',
        amount: 60,
        unit: 'g',
        recipeId: 'basecreamvanilla',
      },
    ],
    instructions: [],
  },
  {
    name: 'Ciasto jogurtowe',
    recipeId: 'dessertyogurtcake',
    defaultWeight: 900,
    ingredients: [
      { name: 'Jogurt naturalny', amount: 200, unit: 'g' },
      { name: 'Cukier', amount: 150, unit: 'g' },
      { name: 'Mąka pszenna', amount: 250, unit: 'g' },
      { name: 'Olej', amount: 120, unit: 'ml' },
      { name: 'Jajka', amount: 150, unit: 'g' },
    ],
    instructions: [],
  },
  {
    name: 'Czekoladowa rolada',
    recipeId: 'dessertchocoroll',
    defaultWeight: 1000,
    ingredients: [
      { name: 'Biszkopt', amount: 300, unit: 'g', recipeId: 'basesponge' },
      {
        name: 'Ganache czekoladowy',
        amount: 300,
        unit: 'g',
        recipeId: 'baseganache',
      },
      { name: 'Dżem malinowy', amount: 100, unit: 'g' },
    ],
    instructions: [],
  },
  {
    name: 'Mus czekoladowy',
    recipeId: 'dessertchocomousse',
    defaultWeight: 300,
    ingredients: [
      { name: 'Czekolada 70%', amount: 120, unit: 'g' },
      { name: 'Śmietanka 30%', amount: 150, unit: 'ml' },
      { name: 'Jajka', amount: 100, unit: 'g' },
    ],
    instructions: [],
  },
] satisfies Recipe[];
