import type { BudgetCategory } from './types.ts';

/** Categories verified against the current Budżet 2.0 Ustawienia dictionary. */
export const budgetCategorySeedData = [
  {
    id: 'mieszkanie-czynsz-i-kredyt',
    group: null,
    category: 'Mieszkanie',
    subcategory: 'Czynsz i kredyt',
  },
  { id: 'mieszkanie-media', group: null, category: 'Mieszkanie', subcategory: 'Media' },
  { id: 'mieszkanie-subskrypcje', group: null, category: 'Mieszkanie', subcategory: 'Subskrypcje' },
  { id: 'samochod-paliwo', group: null, category: 'Samochód', subcategory: 'Paliwo' },
  { id: 'samochod-parking', group: null, category: 'Samochód', subcategory: 'Parking' },
  {
    id: 'samochod-serwis-i-oplaty',
    group: null,
    category: 'Samochód',
    subcategory: 'Serwis i opłaty',
  },
  { id: 'zycie-zywnosc', group: null, category: 'Życie', subcategory: 'Żywność' },
  {
    id: 'zycie-jedzenie-poza-domem',
    group: null,
    category: 'Życie',
    subcategory: 'Jedzenie poza domem',
  },
  { id: 'zycie-transport', group: null, category: 'Życie', subcategory: 'Transport' },
  { id: 'zycie-dziecko', group: null, category: 'Życie', subcategory: 'Dziecko' },
  { id: 'zycie-inne', group: null, category: 'Życie', subcategory: 'Inne' },
  {
    id: 'utrzymanie-domu-naprawy',
    group: null,
    category: 'Utrzymanie domu',
    subcategory: 'Naprawy',
  },
  {
    id: 'utrzymanie-domu-wyposazenie-i-sprzet',
    group: null,
    category: 'Utrzymanie domu',
    subcategory: 'Wyposażenie i sprzęt',
  },
  {
    id: 'osobiste-zakupy-i-uslugi',
    group: null,
    category: 'Osobiste',
    subcategory: 'Zakupy i usługi',
  },
  { id: 'zdrowie-leki', group: null, category: 'Zdrowie', subcategory: 'Leki' },
  { id: 'zdrowie-leczenie', group: null, category: 'Zdrowie', subcategory: 'Leczenie' },
  { id: 'rozrywka-subskrypcje', group: null, category: 'Rozrywka', subcategory: 'Subskrypcje' },
  { id: 'rozrywka-podroze', group: null, category: 'Rozrywka', subcategory: 'Podróże' },
  {
    id: 'rozrywka-hobby-i-kultura',
    group: null,
    category: 'Rozrywka',
    subcategory: 'Hobby i kultura',
  },
  { id: 'rozrywka-inne', group: null, category: 'Rozrywka', subcategory: 'Inne' },
  {
    id: 'rozwoj-osobisty-sport-i-edukacja',
    group: null,
    category: 'Rozwój osobisty',
    subcategory: 'Sport i edukacja',
  },
  { id: 'finanse-praca', group: null, category: 'Finanse', subcategory: 'Praca' },
  {
    id: 'finanse-inwestycje-i-akcje',
    group: null,
    category: 'Finanse',
    subcategory: 'Inwestycje i akcje',
  },
  {
    id: 'finanse-podatki-i-ubezpieczenia',
    group: null,
    category: 'Finanse',
    subcategory: 'Podatki i ubezpieczenia',
  },
  { id: 'finanse-pozostale', group: null, category: 'Finanse', subcategory: 'Pozostałe' },
  { id: 'lucjan-utrzymanie', group: null, category: 'Lucjan', subcategory: 'Utrzymanie' },
  { id: 'lucjan-weterynarz', group: null, category: 'Lucjan', subcategory: 'Weterynarz' },
  {
    id: 'okolicznosciowe-prezenty-i-okazje',
    group: null,
    category: 'Okolicznościowe',
    subcategory: 'Prezenty i okazje',
  },
  {
    id: 'dzialka-ogrod-i-dzialka',
    group: null,
    category: 'Działka',
    subcategory: 'Ogród i działka',
  },
  {
    id: 'wylaczone-operacje-techniczne',
    group: null,
    category: 'Wyłączone',
    subcategory: 'Operacje techniczne',
  },
] satisfies BudgetCategory[];
